//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviaSession1.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlLogin
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UnsuccefulLogout { get; set; }
        public Nullable<byte> Crash { get; set; }
    
        public virtual User User { get; set; }
    }
}
